language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - make install
script:
  - make lint
  - make lint-docs
  - if [ $TRAVIS_PYTHON_VERSION -eq "3.6" ] ; then make type-check fi
  - make test-with-coverage
  - coveralls
