language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - make install
script:
  - make lint
  - make lint-docs
  - make test-with-coverage
  - coverage report --omit=setup.py pymonet/test_*.py
  - coveralls
